#n = input('Digite um valor de 0 a 9999: ')
#print(f'Unidade: {n[3]}')
#print(f'Dezena:  {n[2]}')
#print(f'Centena: {n[1]}')
#print(f'Milhar:  {n[0]}')
n = int(input('Digite um valor de 0 a 9999: '))
n = str(n)
print(f'Unidade: {n[3]}')
print(f'Dezena:  {n[2]}')
print(f'Centena: {n[1]}')
print(f'Milhar:  {n[0]}')