Tabuada = int(input("Digite um número: "))
print(f"A tabuada de {Tabuada} é:")
print(f"{Tabuada} x 1 = {Tabuada * 1}")
print(f"{Tabuada} x 2 = {Tabuada * 2}")
print(f"{Tabuada} x 3 = {Tabuada * 3}")
print(f"{Tabuada} x 4 = {Tabuada * 4}")
print(f"{Tabuada} x 5 = {Tabuada * 5}")
print(f"{Tabuada} x 6 = {Tabuada * 6}")
print(f"{Tabuada} x 7 = {Tabuada * 7}")
print(f"{Tabuada} x 8 = {Tabuada * 8}")
print(f"{Tabuada} x 9 = {Tabuada * 9}")
print(f"{Tabuada} x 10 = {Tabuada * 10}")
